base { archivesName = "MineTranslator-${minecraft_version}" }

sourceSets.main.java.srcDir '../../universal-ports/mod/src/main/java'
sourceSets.main.resources.srcDir '../../universal-ports/mod/src/main/resources'

dependencies {
    compileOnly project(':library')
    runtimeOnly project(':library')
    compileOnly 'com.google.code.gson:gson:2.8.0'
}

processResources {
    inputs.property 'version', mod_version
    inputs.property 'minecraft_version', minecraft_version
    filesMatching('fabric.mod.json') {
        expand(version: mod_version, minecraft_version: minecraft_version)
    }
}
