modLoader = "javafml"
loaderVersion = "[1,)"
clientSideOnly = true
displayURL = "https://github.com/NotKingChoka/MineTranslator"
issueTrackerURL = "https://github.com/NotKingChoka/MineTranslator/issues"
logoFile = "icon.png"
authors = "NotKingChoka"
credits = "Compatibility Library for MineTranslator"
license = "MIT"

[[mods]]
modId = "minetranslator-compat"
version = "${version}"
displayName = "MineTranslator Compatibility Library"
description = '''
A compatibility library for MineTranslator containing mixins and GUI renderers.
'''

[[dependencies.minetranslator-compat]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.minetranslator-compat]]
modId = "minetranslator"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"


