modLoader = "javafml"
loaderVersion = "[1,)"
clientSideOnly = true
displayURL = "https://www.curseforge.com/minecraft/mc-mods/MineTranslator"
issueTrackerURL = "https://github.com/pSUNSET/MineTranslator/issues"
logoFile = "icon.png"
authors = "NotKingChoka"
credits = "Everyone who contributed to this mod"
license = "MIT"

[[mods]]
modId = "minetranslator"
version = "${version}"
displayName = "Translator++"
description = '''
A mod for swift, light and convenient auto translation.
'''

[[dependencies.minetranslator]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.minetranslator]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_neoforge_range}"
ordering = "NONE"
side = "CLIENT"
